Intmdb 419 network peering
mongodb/mongodbatlas-cloudformation-resources pull request #131
Opened 2022-10-28 20:52 UTC by govardhanpagidi

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

- Added Validations for all method inputs. 
- Added error handling.

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run `make fmt` and formatted my code

## Further comments

2022-11-01 08:57 UTC, andreaangiolillo commented on cfn-resources/network-peering/cmd/resource/resource.go
> +}
Please define


```
const (
	publicKey    = "ApiKeys.PublicKey"
	privateKey   = "ApiKeys.PrivateKey"
	projectId    = "ProjectId"
......
)
```
then 
```
var CreateRequiredFields = []string{publicKey, privateKey, projected, .....}
```

2022-11-01 08:57 UTC, andreaangiolillo commented on cfn-resources/network-peering/cmd/resource/resource.go
> +	}
```suggestion
	if modelValidation := validateModel(CreateRequiredFields, currentModel); modelValidation != nil {
		return *modelValidation, nil
	}
```

2022-11-01 08:57 UTC, andreaangiolillo commented on cfn-resources/network-peering/cmd/resource/resource.go
> +	}
```suggestion
	if modelValidation := validateModel(CreateRequiredFields, currentModel); modelValidation != nil {
		return *modelValidation, nil
	}
```

2022-11-01 08:57 UTC, andreaangiolillo commented on cfn-resources/network-peering/cmd/resource/resource.go
> +	}
```suggestion
	if modelValidation := validateModel(CreateRequiredFields, currentModel); modelValidation != nil {
		return *modelValidation, nil
	}
```

2022-11-01 08:57 UTC, andreaangiolillo commented on cfn-resources/network-peering/cmd/resource/resource.go
> +	}
```suggestion
	if modelValidation := validateModel(CreateRequiredFields, currentModel); modelValidation != nil {
		return *modelValidation, nil
	}
```

2022-11-01 08:57 UTC, andreaangiolillo commented on cfn-resources/network-peering/cmd/resource/resource.go
> +	}
```suggestion
	if modelValidation := validateModel(CreateRequiredFields, currentModel); modelValidation != nil {
		return *modelValidation, nil
	}
```

2022-11-01 08:57 UTC, andreaangiolillo commented on cfn-resources/util/validator/validator_test.go
> +var ListRequiredFields = []string{"ApiKeys.PublicKey", "ApiKeys.PrivateKey", "ClusterName", "ProjectId"}
Same as above

2022-11-09 09:38 UTC, andreaangiolillo approved these changes
LGTM

2022-11-09 09:38 UTC, andreaangiolillo commented on cfn-resources/network-peering/cmd/resource/resource.go
> +	// TODO add logging here
```suggestion
```

2022-11-10 02:54 UTC, Zuhairahmed requested changes
Missing updates to docs + README file, can you please add to this PR?

2022-11-11 02:38 UTC, Zuhairahmed approved these changes
LGTM

2022-11-11 03:54 UTC, ParthasarathyVaradhan approved these changes
LGTM

2022-11-11 03:55 UTC, merged