INTMDB-462-teams module implementation
mongodb/mongodbatlas-cloudformation-resources pull request #156
Opened 2022-11-28 14:44 UTC by rdharmedran

## Description

Teams resource implementation for AWS CFN
Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

## Further comments

2022-11-30 09:52 UTC, andreaangiolillo commented on cfn-resources/teams/cmd/resource/resource.go
> +	}
`ValidateRequest` should only validate the request. it should not create the client and the event as well

```suggestion
	err := ValidateRequest(CreateRequiredFields, currentModel); err !=nill{
		return nill, err
	}
```

2022-11-30 09:52 UTC, andreaangiolillo commented on cfn-resources/teams/cmd/resource/resource.go
> +	}
same

2022-11-30 09:52 UTC, andreaangiolillo commented on cfn-resources/teams/cmd/resource/resource.go
> +	}
same

2022-11-30 09:52 UTC, andreaangiolillo commented on cfn-resources/teams/cmd/resource/resource.go
> +	}
same

2022-11-30 09:52 UTC, andreaangiolillo commented on cfn-resources/teams/cmd/resource/resource.go
> +	}
this piece of code has a lot of nested if. Could you refactor it? moving some parts to specific functions would improve readability

2022-11-30 09:52 UTC, andreaangiolillo commented on cfn-resources/util/constants/constants.go
> +	TeamID = "TeamId"
```suggestion
	TeamID = "TeamId"
```

2022-11-30 14:01 UTC, rdharmedran commented
@andreaangiolillo  we have fixed all review comment.Please check

2022-11-30 14:03 UTC, andreaangiolillo approved these changes
LGTM

2022-12-01 00:33 UTC, Zuhairahmed requested changes
Thanks @rdharmedran. Since this one is missing a few key functions as below that are not in go-client can you: 1) create separate PR building out those functions and 2) build in that added functionality into this CloudFormation resource PR. Let me know if you need to discuss 

GET - [https://cloud.mongodb.com/api/atlas/v1.0/groups/{groupId}/teams](https://cloud.mongodb.com/api/atlas/v1.0/groups/%7BgroupId%7D/teams)
DELETE - [https://cloud.mongodb.com/api/atlas/v1.0/groups/{groupId}/teams/{teamId}](https://cloud.mongodb.com/api/atlas/v1.0/groups/%7BgroupId%7D/teams/%7BteamId%7D)
POST - [https://cloud.mongodb.com/api/atlas/v1.0/groups/{groupId}/teams](https://cloud.mongodb.com/api/atlas/v1.0/groups/%7BgroupId%7D/teams)

2022-12-09 14:40 UTC, rdharmedran commented
> Thanks @rdharmedran. Since this one is missing a few key functions as below that are not in go-client can you: 1) create separate PR building out those functions and 2) build in that added functionality into this CloudFormation resource PR. Let me know if you need to discuss
> 
> GET - [https://cloud.mongodb.com/api/atlas/v1.0/groups/{groupId}/teams](https://cloud.mongodb.com/api/atlas/v1.0/groups/%7BgroupId%7D/teams) DELETE - [https://cloud.mongodb.com/api/atlas/v1.0/groups/{groupId}/teams/{teamId}](https://cloud.mongodb.com/api/atlas/v1.0/groups/%7BgroupId%7D/teams/%7BteamId%7D) POST - [https://cloud.mongodb.com/api/atlas/v1.0/groups/{groupId}/teams](https://cloud.mongodb.com/api/atlas/v1.0/groups/%7BgroupId%7D/teams)

@Zuhairahmed  We have implemented these APIs in this cloud formation module.Please review

2022-12-09 15:52 UTC, Zuhairahmed commented
> > Thanks @rdharmedran. Since this one is missing a few key functions as below that are not in go-client can you: 1) create separate PR building out those functions and 2) build in that added functionality into this CloudFormation resource PR. Let me know if you need to discuss
> > GET - [https://cloud.mongodb.com/api/atlas/v1.0/groups/{groupId}/teams](https://cloud.mongodb.com/api/atlas/v1.0/groups/%7BgroupId%7D/teams) DELETE - [https://cloud.mongodb.com/api/atlas/v1.0/groups/{groupId}/teams/{teamId}](https://cloud.mongodb.com/api/atlas/v1.0/groups/%7BgroupId%7D/teams/%7BteamId%7D) POST - [https://cloud.mongodb.com/api/atlas/v1.0/groups/{groupId}/teams](https://cloud.mongodb.com/api/atlas/v1.0/groups/%7BgroupId%7D/teams)
> 
> @Zuhairahmed We have implemented these APIs in this cloud formation module.Please review

Makes sense, thanks for the update here @rdharmedran. LGTM.

2022-12-09 15:53 UTC, Zuhairahmed approved these changes

2022-12-12 12:29 UTC, govardhanpagidi approved these changes

2022-12-12 14:45 UTC, merged