Feature private endpoint regional mode
mongodb/mongodbatlas-cloudformation-resources pull request #173
Opened 2022-12-19 13:00 UTC by govardhanpagidi

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run `make fmt` and formatted my code

## Further comments

2022-12-19 13:59 UTC, rdharmedran approved these changes
LGTM

2022-12-19 20:48 UTC, Zuhairahmed commented
Please resolve branch conflicts

2022-12-19 20:50 UTC, Zuhairahmed commented
Missing GitHub Build + Linting Error checks, please add

2022-12-19 20:51 UTC, Zuhairahmed commented on cfn-resources/private-endpoint-regional-mode/README.md
> +
Missing Example section, please add and link to Examples folder: https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples

2022-12-19 20:53 UTC, Zuhairahmed commented on examples/private-endpoint-regional-mode/privateEndpointRegionalMode.json
> +  "Description" : "This template creates a Project on the MongoDB Atlas API, this will be billed to your Atlas account.",
This appears to be for Project resource. Please update for Private Endpoint Regional Mode

2022-12-19 20:54 UTC, Zuhairahmed requested changes
Thanks @govardhanpagidi! Few comments if you can please address and then ping in Slack to review again when ready. Otherwise great work!

2022-12-21 16:38 UTC, Zuhairahmed commented on cfn-resources/private-endpoint-regional-mode/README.md
> +Please see the [CFN Template](test/private-endpoint-regional-mode.sample-cfn-request.json) for example resource
```suggestion
Please see the [Private Endpoint Regional Mode](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples/private-endpoint-regional-mode) for example resource
```

2022-12-21 16:39 UTC, Zuhairahmed approved these changes
@govardhanpagidi few more minor doc comments, please review. Otherwise not blocking, LGTM

2022-12-21 16:40 UTC, Zuhairahmed commented
Also please resolve branch conflicts + Missing GitHub Build + Linting Error checks, please add

2022-12-21 17:22 UTC, ParthasarathyVaradhan approved these changes

2022-12-22 11:55 UTC, matt-condon approved these changes

2022-12-22 13:14 UTC, merged