INTMDB-528-Feature custom dns config cluster aws
mongodb/mongodbatlas-cloudformation-resources pull request #176
Opened 2022-12-19 13:07 UTC by govardhanpagidi

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

## Further comments

2022-12-19 14:14 UTC, rdharmedran commented on cfn-resources/custom-dns-configuration-cluster-aws/cmd/resource/resource.go
> +var UpdateRequiredFields []string
use one array variable if all the input fields are same for create,read,delete,list

2022-12-19 20:34 UTC, Zuhairahmed commented on cfn-resources/custom-dns-configuration-cluster-aws/README.md
> +Returns, adds and removes custom dns configuration for AWS cluster.
```suggestion
Returns, adds and removes custom DNS configurations for MongoDB Atlas database deployments on AWS.
```

2022-12-19 20:35 UTC, Zuhairahmed commented on cfn-resources/custom-dns-configuration-cluster-aws/README.md
> +For more information see: MongoDB Atlas API [CustomeDNSConfigurationClusterAWS Endpoint](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Custom-DNS-for-Atlas-Clusters-Deployed-to
```suggestion
For more information see: MongoDB Atlas API Endpoint [Custom DNS for Atlas Clusters Deployed to AWS](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Custom-DNS-for-Atlas-Clusters-Deployed-to-AWS) Documentation.
```

2022-12-19 20:37 UTC, Zuhairahmed commented on cfn-resources/custom-dns-configuration-cluster-aws/README.md
> +
Missing Example Section, can you add and link to Example directory: https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples

2022-12-19 20:38 UTC, Zuhairahmed commented on examples/custom-dns-configuration-cluster-aws/customDnsConfigurationClusterAws.json
> +  "Description" : "This template creates a Project on the MongoDB Atlas API, this will be billed to your Atlas account.",
This looks like Example for Project Resource. Can you refresh for custom DNS Configuration Cluster AWS

2022-12-19 20:40 UTC, Zuhairahmed requested changes
Few comments, can you resolve and then ping me on Slack to review again when ready. thanks and great work here @govardhanpagidi!

2022-12-19 20:49 UTC, Zuhairahmed commented
Missing GitHub Build + Linting Error checks, please add

2022-12-20 17:11 UTC, ParthasarathyVaradhan commented
Build and Lint Checks are happening.
https://github.com/mongodb/mongodbatlas-cloudformation-resources/actions/runs/3742624161/jobs/6353800277
https://github.com/mongodb/mongodbatlas-cloudformation-resources/actions/runs/3742624165/jobs/6353800293

2022-12-21 18:57 UTC, Zuhairahmed commented on cfn-resources/custom-dns-configuration-cluster-aws/README.md
> +## CloudFormation Examples
```suggestion
## CloudFormation Example
```

2022-12-21 18:58 UTC, Zuhairahmed commented on cfn-resources/custom-dns-configuration-cluster-aws/README.md
> +Please see the [CFN Template](test/custom-dns-config-cluster-aws.sample-cfn-request.json) for example resource
```suggestion
Please see the [custom-dns-configuration-cluster-aws](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples/custom-dns-configuration-cluster-aws) for example resource
```

2022-12-21 18:58 UTC, Zuhairahmed approved these changes
Few minor comments, please fix. Not blocking. Otherwise LGTM! thanks @govardhanpagidi

2022-12-22 04:49 UTC, ParthasarathyVaradhan approved these changes
LGTM. Build file is correct for Multi region deployment

2022-12-22 14:47 UTC, swattyT approved these changes
LGTM!

2022-12-22 15:06 UTC, merged